from __future__ import annotations

VALIDATION_HORIZONS: tuple[int, ...] = (5, 10, 20, 60)

MIN_IC_SAMPLE_SIZE = 5

VALIDATION_STATUS_PENDING = "pending"
VALIDATION_STATUS_COMPLETED = "completed"
VALIDATION_STATUS_INSUFFICIENT_DATA = "insufficient_data"
VALIDATION_STATUS_FAILED = "failed"

HORIZON_STATUS_OK = "ok"
HORIZON_STATUS_INSUFFICIENT_DATA = "insufficient_data"

TREND_REGIME_BULL = "BULL"
TREND_REGIME_BEAR = "BEAR"
TREND_REGIME_SIDEWAYS = "SIDEWAYS"  # 3-way only: range-bound / no clear trend

VOL_REGIME_HIGH = "HIGH_VOL"
VOL_REGIME_LOW = "LOW_VOL"

DEFAULT_HIGH_VOL_THRESHOLD = 0.20
REGIME_MA_WINDOW = 200
REGIME_VOL_WINDOW = 20
REGIME_SMA50_WINDOW = 50
REGIME_SLOPE_LOOKBACK = 20  # bars back to measure the 200-SMA slope (3-way regime)
REGIME_SLOPE_FLAT_PCT = 0.005  # |200-SMA 20-bar slope| below this = flat → SIDEWAYS

MAX_FORWARD_TRADING_DAYS = max(VALIDATION_HORIZONS)

FULL_UNIVERSE_CAMPAIGN_STATUS_PENDING = "pending"
FULL_UNIVERSE_CAMPAIGN_STATUS_RUNNING = "running"
FULL_UNIVERSE_CAMPAIGN_STATUS_COMPLETED = "completed"
FULL_UNIVERSE_CAMPAIGN_STATUS_FAILED = "failed"

FULL_UNIVERSE_RUN_STATUS_PENDING = "pending"
FULL_UNIVERSE_RUN_STATUS_COMPLETED = "completed"
FULL_UNIVERSE_RUN_STATUS_FAILED = "failed"
FULL_UNIVERSE_RUN_STATUS_SKIPPED = "skipped"
