from __future__ import annotations

VALIDATION_HORIZONS: tuple[int, ...] = (5, 10, 20, 60)

MIN_IC_SAMPLE_SIZE = 5

VALIDATION_STATUS_PENDING = "pending"
VALIDATION_STATUS_COMPLETED = "completed"
VALIDATION_STATUS_INSUFFICIENT_DATA = "insufficient_data"
VALIDATION_STATUS_FAILED = "failed"

HORIZON_STATUS_OK = "ok"
HORIZON_STATUS_INSUFFICIENT_DATA = "insufficient_data"

TREND_REGIME_BULL = "BULL"
TREND_REGIME_BEAR = "BEAR"

VOL_REGIME_HIGH = "HIGH_VOL"
VOL_REGIME_LOW = "LOW_VOL"

DEFAULT_HIGH_VOL_THRESHOLD = 0.20
REGIME_MA_WINDOW = 200
REGIME_VOL_WINDOW = 20

MAX_FORWARD_TRADING_DAYS = max(VALIDATION_HORIZONS)
