from __future__ import annotations

from decimal import Decimal

MIN_EXIT_SAMPLE_SIZE = 30
PERSIST_COMMIT_INTERVAL = 25
PERSIST_PROGRESS_INTERVAL = 10
SIMULATION_PERCENT_CAP = 90.0
PERSISTENCE_PERCENT_FLOOR = 90.0
INSUFFICIENT_SAMPLE_STATUS = "INSUFFICIENT_SAMPLE_SIZE"
DEFAULT_RESEARCH_HORIZON = 20
ALPHA_DECAY_MAX_DAYS = 60
ATR_TRAIL_MULTIPLIER = Decimal("2.0")
BREAKOUT_LOOKBACK_DAYS = 63

POLICY_FAMILY_FIXED_HOLD = "FIXED_HOLD"
POLICY_FAMILY_RANK_DETERIORATION = "RANK_DETERIORATION"
POLICY_FAMILY_REGIME_EXIT = "REGIME_EXIT"
POLICY_FAMILY_TREND_FAILURE = "TREND_FAILURE"
POLICY_FAMILY_ALPHA_DECAY = "ALPHA_DECAY"

FIXED_HOLD_DAYS: tuple[int, ...] = (5, 10, 15, 20, 30, 40, 60)
RANK_EXIT_THRESHOLDS: tuple[int, ...] = (50, 60, 70, 80, 90)
REGIME_EXIT_VARIANTS: tuple[str, ...] = (
    "REGIME_IMMEDIATE",
    "REGIME_DELAY_3",
    "REGIME_DELAY_5",
    "REGIME_NEVER",
)
TREND_FAILURE_VARIANTS: tuple[str, ...] = (
    "TREND_DMA20_BREAK",
    "TREND_DMA50_BREAK",
    "TREND_BREAKOUT_FAILURE",
    "TREND_ATR_TRAIL",
)

REGIME_LABEL_ALL = "ALL"
REGIME_LABELS: tuple[str, ...] = (
    "BULL_LOW_VOL",
    "BULL_HIGH_VOL",
    "BEAR_LOW_VOL",
    "BEAR_HIGH_VOL",
)

SNAPSHOT_RETURN_DAYS: frozenset[int] = frozenset({5, 10, 20, 60})

BOOTSTRAP_SAMPLE_COUNT = 1000
BOOTSTRAP_CONFIDENCE = 0.95
BOOTSTRAP_SEED = 42
