from __future__ import annotations

from datetime import date

FACTOR_ANALYTICS_HORIZONS: tuple[int, ...] = (5, 10, 20, 60)

DATASET_SPLIT_ALL = "ALL"
DATASET_SPLIT_TRAIN = "TRAIN"
DATASET_SPLIT_HOLDOUT = "HOLDOUT"
DATASET_SPLITS: tuple[str, ...] = (DATASET_SPLIT_ALL, DATASET_SPLIT_TRAIN, DATASET_SPLIT_HOLDOUT)

REGIME_LABEL_ALL = "ALL"
REGIME_LABELS: tuple[str, ...] = (
    "BULL_LOW_VOL",
    "BULL_HIGH_VOL",
    "BEAR_LOW_VOL",
    "BEAR_HIGH_VOL",
)

MIN_FACTOR_SAMPLE_SIZE = 30
MIN_DAILY_IC_SAMPLE_SIZE = 30

DEFAULT_HOLDOUT_START_DATE = date(2025, 1, 1)

BOOTSTRAP_SAMPLE_COUNT = 1000
BOOTSTRAP_CONFIDENCE = 0.95
BOOTSTRAP_METHOD = "daily_ic_resample_with_replacement"
BOOTSTRAP_SEED = 42

STABILITY_STABLE_THRESHOLD = 0.70
STABILITY_MODERATE_THRESHOLD = 0.50

COVERAGE_SPARSE_THRESHOLD = 0.05
COVERAGE_LOW_THRESHOLD = 0.15

CONFIDENCE_LOW_MAX_SAMPLE = 49
CONFIDENCE_MEDIUM_MIN_SAMPLE = 50

DRIFT_OVERFIT_TRAIN_IC = 0.03
DRIFT_OVERFIT_HOLDOUT_IC = 0.01
